openapi: 3.0.0
info:
  title: preading-list-api
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /books:
    post:
      tags:
        - default
      summary: create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 2
                title: To Kill a Mockingbird
                author: Harper Lee
                status: READ
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - default
      summary: update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 0
                title: Gulliver's Travels
                author: Jonathan Swift
                status: READ
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: get
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: delete
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
